### ISSUE TITLE
SAMbA Source code missing

### ISSUE THREAD

**Issue by stain** [UFFeScience/SAMbA#1]
The examples use imports from `br.uff.spark.advancedpipe.*`, but the source code for this package is nowhere to be found.  Should it have been included in this repository?

**Comment by thaylongs** [comment]
Hello.

Thanks for reporting the issue.

We did include package ``br.uff.spark.advancedpipe`` in the Docker image, but you may have experienced a "double import" problem.

After the verification of README, I found  the line:

``import import br.uff.spark.advancedpipe.{ExecutionPlanning, FileElement}``

with keyword ``import`` typed twice.

If you are using the sample provided in the README.md, so this is likely the problem.

I already fixed the documentation.

Let me know if it worked.
Regards,

**Comment by joao-parana** [comment]
I found the class files only on /SAMbAFiles/SAMbA/jars/spark-core_2.11-2.4.0-SNAPSHOT.jar inside the container. Is this correct ?
